---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-docker
  labels:
    app: wordpress-docker
  annotations:
    monitoring: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-docker
  template:
    metadata:
      labels:
        app: wordpress-docker
    spec:
      containers:
        - env:
            - name: WHATEVER_ENV
              value: WHATEVER_VALUE
          image: zavenx/wordpress-docker
          imagePullPolicy: Always
          name: wordpress-docker
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-docker-service
spec:
  selector:
    app: wordpress-docker
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer